### ISSUE TITLE
MenuBox text position a matter of error

### ISSUE THREAD

**Issue by krumaska** [LatteCode/Frontend#9]
**font height**  
1st Menu Box - 100%  
2st Menu Box - 120%  
3st Menu Box - 120%  
This configuration requires two components.  
How can I organize this into one component?   
  
In my case...  

**one component**
```
<MenuBox imgPath: ... fontHeight: 100%>
<MenuBox imgPath: ... fontHeight: 120%>
<MenuBox imgPath: ... fontHeight: 120%>
```    
or  
**two components**  
```
<FirstMenuBox imgPath: ... >
<MenuBox imgPath: ... >
<MenuBox imgPath: ... >
```
  
Is there any better way than this?    
Add, I'm not sure if this is exactly centered from the second box.    
  
- **Pixel 2 XL Resolution** 

![image](https://user-images.githubusercontent.com/51515055/83939659-970bc080-a819-11ea-8069-03530e1ee407.png)

**Comment by CXZ7720** [comment]
The best way is define different style class and adjust each of them.
And one more thing, In nomal case, font size should not use ratio. Use em or rem instead.
